name: expensive
description: "A modern expense tracker app with local storage."
publish_to: 'none'
version: 2.0.0

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  
  # Database
  sqflite: ^2.3.2
  sqflite_common_ffi: ^2.3.2+1
  path: ^1.8.3
  path_provider: ^2.1.2
  
  # State Management
  flutter_riverpod: ^2.5.1
  
  # Storage
  shared_preferences: ^2.2.2
  
  # UI Components
  fl_chart: ^0.66.2
  google_fonts: ^6.1.0
  intl: ^0.19.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1

flutter:
  uses-material-design: true
